### ISSUE TITLE
Add newer ways to print "Hello, World!" in Python.

### ISSUE THREAD

**Issue by Goku-kun** [Goku-kun/1000-ways-to-print-hello-world-in-python#119]
After reviewing the existing ways to print "Hello, World!" in this repository, come up with a new and unique way to print "Hello, World!".

This issue will be kept open for the duration of Hacktoberfest 2022. Happy coding!

**Comment by paras3624** [comment]
Hey! I would like to contribute to this issue. Please assign me this task.

**Comment by Goku-kun** [comment]
Hi, @paras3624. 

I'll be keeping this issue open for the duration of this Hacktoberfest. This means if I assign this issue to anyone, it'll be closed when that person submits a PR against it. You can refer to the guidelines and submit a direct pull request. I'll review all PRs and merge them if they're valid. If you have more questions, let me know. Looking forward to your PR! 😄
