### ISSUE TITLE
Print "Hello, World!" without using the Python print function

### ISSUE THREAD

**Issue by Goku-kun** [Goku-kun/1000-ways-to-print-hello-world-in-python#27]
This challenge dictates to create a python program which prints "Hello, World!" without using the python print function. This idea is based on the python program [link-to-the-program](https://github.com/Goku-kun/1000-ways-to-print-hello-world-in-python/blob/master/using-sys-stdout.py) by @shreeharinw

**Comment by bibliofilo** [comment]
Hi @Goku-kun,  can I give this a shot?

**Comment by Goku-kun** [comment]
Hello, @bibliofilo . Sure! Knock it out!

**Comment by bibliofilo** [comment]
Thanks! I ended up learning about stdout and stderr. Here's the pull request, #33

**Comment by Harivind** [comment]
Hi @Goku-kun, is this still open?

**Comment by Goku-kun** [comment]
@Harivind Yes, this issue is still open.

**Comment by qdtroemner** [comment]
@Goku-kun , I believe this issue has been resolved by the merge in request [#33](https://github.com/Goku-kun/1000-ways-to-print-hello-world-in-python/pull/33).
