### ISSUE TITLE
Add newer ways to print "Hello, World!" in python

### ISSUE THREAD

**Issue by Goku-kun** [Goku-kun/1000-ways-to-print-hello-world-in-python#58]
This issue will be kept open for the duration of Hacktoberfest 2021.

**Comment by codewith-arijit** [comment]
Hi, Can you assign it, to me. Would like to participate in this Hacktoberfest this year.

**Comment by dhruvjain896** [comment]
Hi @Goku-kun , Can you please assign this issue to me.

**Comment by Goku-kun** [comment]
Hey, @dhruvjain896.
This is an open issue and hence, there's no need to assign it to anyone. Submit the pull request and I'll approve it if it follows all the guidelines.

**Comment by dhruvjain896** [comment]
@Goku-kun Please review my pull request #73 add using-user-input.

**Comment by darahaas15** [comment]
@Goku-kun could you please review pr #96
