### ISSUE TITLE
Print Hello, World in python in the worst way possible.

### ISSUE THREAD

**Issue by Goku-kun** [Goku-kun/1000-ways-to-print-hello-world-in-python#9]
This issue is opened to come up with different overkill ways to print "Hello, World!" in python. This issue is opened based on the idea provided by @funwaa and you can refer these codes [print hello world using moons](https://github.com/Goku-kun/1000-ways-to-print-hello-world-in-python/blob/master/using-moons.py) and [generating the correct ascii character with random function to print Hello, World!](https://github.com/Goku-kun/1000-ways-to-print-hello-world-in-python/blob/master/using-random.py) as examples to your coding adventure. Happy coding!

**Comment by VishalAmbavade** [comment]
@Goku-kun, I would like to take this challenge

**Comment by nocorners** [comment]
I'd like to take this on, too, please!
